using ServerStatisticsCollectionService.ServerStatisticsCollectors;

namespace ServerStatisticsCollectionService.ServerStatisticsCollectorCreators;

public interface IServerStatisticsCollectorCreator
{
    public IServerStatisticsCollector GetServerStatisticsCollector();
}