using ServerStatisticsCollectionService.ServerStatisticsCollectors;

namespace ServerStatisticsCollectionService.ServerStatisticsCollectorCreator;

public interface IServerStatisticsCollectorCreator
{
    public IServerStatisticsCollector GetServerStatisticsCollectorFor(string osName);
}